---
- hosts: all
  gather_facts: no
  tasks:
  - name: Start bot.js forever process
    become: true
    shell: forever start /home/cibot/app/bot.js
    environment:
      SLACK_TOKEN: #{{ INSERT SLACK TOKEN }}
